### ISSUE TITLE
I wanna contribute to this project

### ISSUE THREAD

**Issue by escobera** [scrogson/franz#1]
Hey there @scrogson!  I really liked the idea of this project and would like to contribute!

I tried to update the project dependencies and run `mix test`, but it just hanged. I'm still a newbie with rust, so I don't really know how to debug this. Would you be willing to give me some pointers on what to look for? 

Thanks in advance! =)

**Comment by escobera** [comment]
I sent a pr #2

I have tried to update the dependencies. When I run a local kafka on port 9094 and try the tests I get:

```
❯ mix test
** (CaseClauseError) no case clause matching: {:error, "Admin operation error: OperationTimedOut (Local: Timed out)"}
    (franz 0.1.0) lib/franz.ex:61: Franz.delete_topic/2
    test/test_helper.exs:1: (file)
    (elixir 1.13.3) lib/code.ex:1183: Code.require_file/2
```

**Comment by escobera** [comment]
Oh, the problem was in my kafka cluster. By using the provided docker-compose I was able to run the tests! \o/
